name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet publish MarkdownToDiscord -c Release -p:PublishSingleFile=true --self-contained true -r linux-x64
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: MarkdownToDiscord
        path: ./MarkdownToDiscord/bin/Release/net7.0/linux-x64/publish/MarkdownToDiscord
        if-no-files-found: error
