name: Build

on:
  push:
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: goto-bus-stop/setup-zig@v2
    - name: Build
      run: zig build -Doptimize=ReleaseSmall
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: MarkdownToDiscord
        path: ./zig-out/bin/MarkdownToDiscord
        if-no-files-found: error
